= Overview of the samples
:navtitleshort-description.adoc: Overview

The samples are structured into uses cases.
Each use case uses different components from the modelix platform
to create custom solutions.

On this page, you can get an overview of all uses cases,
and see how they are related and what their essential differences are.

image::system-diagram-full.svg[]

[#use_case_1]
== Use case 1

In the first use case, an MPS project is synchronized to a repository on a xref:core:reference/component-model-server.adoc[model server]
by utilizing the https://artifacts.itemis.cloud/service/rest/repository/browse/maven-mps/org/modelix/mps/model-server-sync-plugin/[model-server-sync-plugin].

It shows how to make model data, previously accessible only in a running MPS or via files, available through a server.

In itself, this use case has little value, but the next use cases build in part on it.

=== Use case 2

This use case shows how a web backend can access and modify model data that was previously only editable through MPS.

There are two variants of this use case with different backends.
They differ in that variant A connects directly to a running MPS and variant B connects to a model serve,
which can optionally be synchronized with an MPS project.

The model data on the backends is accessed through ab API
generated from the xref:metamodel.adoc[metamodel of the samples]
using the
xref:core:reference/component-model-api-gen-gradle.adoc[Model API generator].

The web backends are accompanied by a web frontend for easy interaction.

=== Variant A

The web backend in this variant is implemented in https://ktor.io[Ktor].
It uses the xref:core:reference/component-light-model-client.adoc[light-model-client] to connect to a running MPS
that exposes its data through the xref:core:reference/component-mps-model-server-plugin.adoc[model-server-plugin].

[#use_case_1_variant_b]
=== Variant B

The web backend in this variant is implemented in https://quarkus.io/[Quarkus].
It uses the https://artifacts.itemis.cloud/service/rest/repository/browse/maven-mps/org/modelix/model-client/[model-client]
to connect to a branch on a xref:core:reference/component-model-server.adoc[model server].

The branch can optionally be kept in sync with an MPS project by using the https://artifacts.itemis.cloud/service/rest/repository/browse/maven-mps/org/modelix/mps/model-server-sync-plugin/[model-server-sync-plugin] like in xref:use_case_1[use case 1]

== Use case 3

Here web frontend directly connects to a model server without an intermediate backend.

It runs a https://artifacts.itemis.cloud/service/rest/repository/browse/maven-mps/org/modelix/model-client/[model-client] directly inside a Single-page application that connects to the model server.

Like in xref:use_case_1_variant_b[variant B of use case 2],
the model server can optionally be synced with a running MPS.

This use case has two clients.
One is an application to edit model data and is written in https://vuejs.org/[Vue.js].
And the other is an application to overview model data and is written with https://angular.io/[Angular].

Both applications use a TypeScript API
generated by the xref:core:reference/component-model-api-gen-gradle.adoc[Model API generator] from the xref:metamodel.adoc[metamodel].







