= Introduction
:navtitle: Introduction

include::partial$short-description.adoc[]

None of the examples try to reuse editors defined in MPS.
If your goal is to reuse MPS editors as is, then modelix itself ships with a https://lp.jetbrains.com/projector/[Projector] integration to achieve this.

While all the examples use the same language defined in MPS they are not meant as one complete example but rather as individual parts.
The purpose of the examples is to give inspiration for what is possible with modelix and make you think about and envision your own use cases.


== Technical prerequisites

To work with the samples, you need the following software installed.:

* MPS `2021.2.6`
* Java 21
* Docker and https://docs.docker.com/compose/[Docker Compose]
+
Alternatives like https://podman.io/[Podman] might work, but have not been tested.

== Getting started

* Clone https://github.com/modelix/modelix.samples[samples repository]
* Start building all components with `./gradlew build` inside the repository
+
NOTE: Building everything in the beginning is not strictly necessary, but it enables you to let the build run, while you explore the documentation further.
+
* Explore the documentation
** Start with the xref:overview.adoc[overview]
** Or go directly to one of the samples
*** xref:use_case_1.adoc[]
*** xref:use_case_2.adoc[]
*** xref:use_case_3.adoc[]
*** xref:monitoring.adoc[]
